trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: CmdLine@2
  inputs:
    script:
      dotnet publish Squil.Maui -o $(Build.BinariesDirectory) -f windows10.0.19041.0
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1    
  displayName: 'Publish Artifact: web'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
