trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: 'Squil.Maui'
    arguments: '-o $(Build.ArtifactStagingDirectory) -f windows10.0.19041.0'
- task: PublishBuildArtifacts@1    
  displayName: 'Publish Artifact: maui'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
