trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: 'Squil.Maui'
    arguments: '-o publish'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'publish'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1    
  displayName: 'Publish Artifact: maui'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
